- name: Backend (Python)
  hosts: schoolpi
  vars:
    program_path: "/home/pi/button"
  tasks:
    - name: apt update
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Installing systemd
      become: yes
      apt:
        name: systemd
        state: present
    - name: Installing python 3.10
      become: yes
      apt:
        name: python3.10
        state: present
    - name: Copying the program
      synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "{{ program_path }}"
        delete: true
        recursive: true

    - name: Linking service file
      become: yes
      file:
        src: "{{ program_path }}/button.service"
        dest: "/lib/systemd/system/button.service"
        state: link
    - name: Changing file premission
      become: yes
      file:
        path: "/lib/systemd/system/button.service"
        mode: 644
    - name: Setting up service
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes
        name: button.service
        enabled: true
    - name: Starting service
      become: yes
      ansible.builtin.systemd:
        daemon-reexec: yes
        state: started
        name: button.service
    - name: Testing service
      command: "service button status"
- name: UI (Flutter)
  hosts: schoolpi
  vars:
    program_path: "/home/pi/button"
  tasks:
    - name: Installing build dependencies
      become: yes
      apt:
        pkg:
          - clang
          - cmake
          - build-essential
          - pkg-config
          - libegl1-mesa-dev
          - libxkbcommon-dev
          - libgles2-mesa-dev
          - libwayland-dev
          - wayland-protocols
          - g++-multilib
          - git
          - python3
          - curl
    - name: Creates tools directory
      file:
        path: /home/pi/build_tools/
        state: directory
    - name: Cloning build tool
      git:
        repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
        version: main
        dest: /home/pi/build_tools/depot_tools
    - name: Creates flutter directory
      file:
        path: /home/pi/flutter/
        state: directory
    - name: Linking gclient file
      become: yes
      file:
        src: "{{ program_path }}/ansible/.gclient"
        dest: "/home/pi/flutter/.gclient"
        state: link
    - name: Downloading flutter source code
      command: chdir=/home/pi/flutter /home/pi/build_tools/depot_tools/gclient sync
    - name: Preparing to build flutter
      command:
        args:
          chdir: /home/pi/flutter/src
        argv:
          - ./flutter/tools/gn
          - --target-os linux
          - --linux-cpu arm64
          - --runtime-mode release
          - --embedder-for-target
          - --disable-desktop-embeddings
          - --no-build-embedder-examples
          - --enable-fontconfig
    - name: Building flutter
      command:
        args:
          chdir: /home/pi/flutter/src
        argv:
          - ninja
          - -C out/linux_release_arm64
    - name: Linking embedded library
      file:
        src: "{{ program_path }}/ansible/.gclient"
        dest: "/home/pi/flutter/.gclient"
        state: link